---
- name: Automate GitHub Release Branch
  hosts: localhost
  connection: local
  vars:
    # 🔴 Replace these placeholders with your actual project details
    github_token: "YOUR_GITHUB_PERSONAL_ACCESS_TOKEN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"
    repo_owner: "amarhjp"
    repo_name: "Aayush"
    base_branch: "main"
    new_branch_name: "release-v1.0"

  tasks:
    - name: Get latest commit SHA from main branch
      ansible.builtin.uri:
        url: "https://github.com{{ repo_owner }}/{{ repo_name }}/git/refs/heads/{{ base_branch }}"
        method: GET
        headers:
          Authorization: "token {{ github_token }}"
          Accept: "application/vnd.github.v3+json"
        status_code: 200
      register: branch_info

    - name: Extract Commit SHA string
      ansible.builtin.set_fact:
        target_sha: "{{ branch_info.json.object.sha }}"

    - name: Create the automated release branch on GitHub
      ansible.builtin.uri:
        url: "https://github.com{{ repo_owner }}/{{ repo_name }}/git/refs"
        method: POST
        headers:
          Authorization: "token {{ github_token }}"
          Accept: "application/vnd.github.v3+json"
        body_format: json
        body:
          ref: "refs/heads/{{ new_branch_name }}"
          sha: "{{ target_sha }}"
        status_code: 201
